# fly.toml app configuration file generated for mouji on 2024-05-21T16:58:22+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'moujidemo'
primary_region = 'sin'

[build]

[env]
  PORT = '8080'

[[mounts]]
  source = 'app_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
